language: swift
osx_image: xcode10.1
xcode_destination: platform=macOS

cache:
  - bundler
  - cocoapods

podfile: Example/Podfile

env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - XCODE_WORKSPACE=Example/CocoaNavigationControllerExample.xcworkspace
  matrix:
  - SCHEME="CocoaNavigationControllerExample"


before_install:
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
 - pod install --project-directory=Example

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build | xcpretty -c
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build | xcpretty -c


notifications:
  slack: $SLACK_CHANNEL